spring:
  application:
    name: Spring Boot Ng
  profiles:
    active: prod

server:
  port: 80

postgres:
  servername: localhost
  port: 5432
  database: ncpj
  username: postgres
  password: 04692225asdASD

mail:
  host: smtp.gmail.com
  port: 587
  username: sottitaa@gmail.com
  password: 04692225asdASD