spring:
  application:
    name: Spring Boot Ng

server:
  port: 8080

postgres:
  servername: localhost
  port: 5432
  database: NCProject
  username: vitya
  password: qwe123asd

mail:
  host: smtp.gmail.com
  port: 587
  username: ivan.viktor.nc@gmail.com
  password: D$h%0WHpdx81